### ISSUE TITLE
unit remaining markers

### ISSUE THREAD

**Issue by Yokon** [Yokon/ChallengerMilsimUnit#2]
Problem: Last five markers remain on OpFor when they die.

Goal: Set markers to only show on last five "alive" OpFor.

**Comment by preacher131** [comment]
Current issue after the enemy dies it not updating the marker to remove it.

**Comment by Yokon** [comment]
It's actually almost a neat little challenge.

**Comment by preacher131** [comment]
Fixed.

#Closed
